"""empty message

Revision ID: 61205a96a6b3
Revises: ab0ebbd8d97d
Create Date: 2023-08-20 03:13:59.464402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61205a96a6b3'
down_revision = 'ab0ebbd8d97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
